name: CI moseiik

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU (for multi-architecture builds)
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Build Docker image for ${{ matrix.arch }}
      run: |
        docker build \
          --platform linux/${{ matrix.arch }} \
          -t moseiik-test:${{ matrix.arch }} .

    - name: Run tests in Docker container for ${{ matrix.arch }}
      run: |
        docker run --rm \
          moseiik-test:${{ matrix.arch }}
